services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
